"""
`BendersSubproblemConfig` -- how `BendersSolver` obtains and solves the second stage.

Parallel to `CGPricingConfig` (`opt/solvers/cg/pricing_config.jl`) and for the same
reason: "where do the route columns come from" is a *search algorithm*, not part of the
model, so two runs differing only in it solve the identical model. Keeping it on the
solver rather than the formulation is what lets an oracle sweep vary one solver and reuse
one formulation.
"""

export BendersSubproblemConfig

"""
    BendersSubproblemConfig(; oracle=:direct_enumeration, max_stops=4,
                              max_routes=200_000, enumeration_time_limit_sec=180.0,
                              time_limit_sec=nothing)

# `oracle`

Where the subproblem's route columns come from.

`:direct_enumeration` enumerates the whole column universe once at build time
(`enumerate_joint_routing_assignment_columns`) and solves every subproblem LP against the
complete pool. Simple and exactly right, but enumerating up front is the cost Benders
exists to avoid, and it forces a small `max_stops`.

`:column_generation` prices each subproblem's columns by label setting instead, so the pool
starts at the two-stop seed and grows on demand, and the formulation's own `max_stops`
applies with no cap.

`:column_generation_activated` is the same, but prices only over the ACTIVATED stations
`S = {j : yhat_j = 1}` and repairs the duals afterwards with a closed-form completion. See
"The activated subproblem" below.

`:column_generation_activated_lpo` prices identically, but replaces the CUT's completion with
a locally Pareto-optimal one chosen against an interior point
(`benders/completion_lpo.jl`). The closed-form bound is deliberately conservative and that
is measurable: at n=10 the plain activated oracle needed 77 cuts over 30 iterations against
5 over 4 for enumeration, for the same optimum. The LPO variant keeps the cheap pricing and
buys back cut strength.

`lpo_completion` picks the completion problem's constraint family (`completion_lpo.jl`):

- `:separation` (default) -- the true rows, seeded from the column pool and generated by
  pricing against each candidate. `lpo_max_rounds` and `lpo_pricing_time_limit_sec` bound it;
  truncating is safe, since it returns the last separation-verified completion and the
  closed-form bound is the initial one. MEASURED at n=10 s=3: **3 Benders iterations / 6
  cuts**, against 30 / 77 for the plain activated oracle.
- `:route_free` -- a sufficient termwise family the activated certificate licenses with NO
  pricing at all. Cheaper per completion, but MEASURED at n=10 s=3 it recovers **none** of
  the strength: 30 iterations / 77 cuts, identical to plain activated, at ~20% of
  separation's per-completion gain. Kept because it is the pricing-free option and the
  comparison is worth being able to re-run, not because it works.

`:column_generation_warm_start` is NOT part of the activated family, despite borrowing its
restriction for one phase. It takes **no dual completion at all**: phase 1 prices built-only
to exhaustion purely to fill the pool, phase 2 then drops the restriction and prices the full
universe to exhaustion, and the cut is read off phase 2's RAW duals by the ordinary argument.
Nothing about its cut needs a new soundness claim -- which is why it is named for what it
does rather than for the restriction it reuses.

It exists to measure one thing. Phase 1 already attains the EXACT `Q_s(yhat)`: a column
touching an unbuilt station is pinned to `theta = 0` by its own `theta - y_j <= 0` row, so it
cannot improve the objective at a fixed `yhat`. Every second of full-station pricing in
`:column_generation` therefore buys DUALS, not value. This arm asks whether warming the pool
first makes that dual-only phase cheaper -- the null hypothesis the two completions above
have to beat.

MEASURED: it beats them. The completions are 40-100% gap at n>=30 with `gain = 0.0` (the
completion falls back to the closed-form bound every call, so the cuts are vacuous), while
this arm certifies n=40 s=3 and n=50 s=3. Its own weakness is different: the split counter
shows phase 1 is under 2% of its pricing, so the warm pool is not shortening phase 2 much --
it is close to plain `:column_generation` with a cheap prologue.

# The activated subproblem and its dual completion

Pricing over all `n` stations when only `k` are built wastes most of the search. The
activated variant restricts it -- and the restriction and the repair are the SAME operation,
which is what makes it cheap and safe.

A column's dual constraint decomposes over its assignment triples, because linking is
per-assignment rather than per-route-node:

    sum_{(p,j,k) in c} [ alpha_p - gammaO_pj - gammaD_pk ]  <=  f_c

Setting `gammaO_pj := max(gammaO_pj, alpha_p)` for every unbuilt `j` (and likewise
`gammaD_pk`) does three things at once:

1. **It restricts the search for free.** `joint_routing_assignment_pricing_candidates`
   computes `rho = alpha_p - gammaO_pj - gammaD_pk - walk` and drops candidates with
   `rho <= 0`, so after the completion every candidate through an unbuilt station is dropped
   by the pricer's own filter. No change to any shared pricing code.
2. **It costs nothing at the anchor.** `yhat_j = 0` for those `j`, so the added terms vanish
   from the dual objective and the cut stays exactly TIGHT at `yhat`.
3. **It restores full-universe dual feasibility.** Any triple touching an unbuilt station now
   has `alpha_p - gamma - gamma <= 0`. For a column `c` mixing such triples with triples
   inside `S`, let `c''` be `c` with the out-of-`S` assignments dropped AND its unbuilt
   visited nodes removed. Then

       sum_{A_in} r <= f_{c''}                        (`c''` is in the searched universe)
       f_{c''} <= f_c - w * sum_{A_out} demand_p * walk_p   (`tau_{c''} <= tau_c`; walk >= 0)
       sum_{A_out} r <= w * sum_{A_out} walk_p        (the completion, per triple; demand >= 1)
       => sum_c r <= f_c.

**Removing the unbuilt nodes is not optional, and this is where the triangle inequality
enters.** The restriction is NOT "routes unrestricted, candidates shrink" -- candidate
generation is reward-driven, so the two are the same thing. `rho <= 0` drops the candidate
(`pricing_round.jl`), `create_joint_routing_assignment_pricing_data` builds
`assignments_by_origin`/`origin_layer_mask` from the survivors only, and both the seed
(`exact/seed.jl`, candidate origins only) and the extension (`exact/extend.jl`, nodes
proposed only from live origins and their opportunities' destinations) read exactly those.
So an unbuilt station leaves the searched ROUTE universe too, and the same-route `c'` is
never searched -- only the shortcut `c''` is. `tau_{c''} <= tau_c` holds because the travel
matrix is required to be metric package-wide (the pricer's age pruning already asserts on
violation).

**`max_wait_time` is not a hazard for that shortcut**, though an earlier version of this
docstring recorded it as one. Both route-feasibility conditions bound ELAPSED durations from
above -- the pickup window is `label.time <= max_wait_time`, the ride limit is
`origin_age + travel <= detour_factor * routing_cost(j,k)` -- and removing a stop only
decreases both. Nothing here measures wait against a fixed request clock, so a shortened
route cannot make a retained passenger wait longer. (`A -> U -> A -> B` with the pickup at
the second `A` is fine too: age is measured from the last visit to that station, so
collapsing the two visits leaves the in-vehicle time unchanged.)

For the same reason, "a column touching an unbuilt station is pinned to `theta = 0` by its
own linking row" -- true of a column with an unbuilt ASSIGNMENT -- does not cover one whose
route merely passes through an unbuilt node. Those are excluded from mattering by being
dominated by their own shortcut, not by being pinned. MEASURED: the restricted solve attains
the exact `Q_s(yhat)` at every anchor tested
(`benchmarks/diagnostics/benders_activated_completion_audit.jl`).

**The price is cut strength, and it is explicit -- and MEASURED at n=10 s=1 seed 42, 8
anchors, against the exact value function over all 86 master-feasible station sets
(`benders_activated_completion_audit.jl`, note `2026-09-10`):**

| | `sum_j Gamma_j / constant` | y where the cut predicts <= 0 | median slack vs true `Q_s` |
| --- | --- | --- | --- |
| closed form | **1.80** | 33.9% | **93.6%** |
| LPO separation | 0.23 | 0.0% | 4.6% |
| full-station CG | 0.22 | 0.0% | 5.1% |

8x the coefficient mass the true dual carries, and a cut sitting a median 93.6% BELOW `Q_s`
-- i.e. saying nothing anywhere but its own anchor. At the optimum the true dual charges
NOTHING for any unbuilt station (a flat `Theta >= 12249.40`); the closed form charges 5210
and 5199 on two of them, and at another anchor 12212 on one station -- 99.7% of the cut's own
constant -- where the truth is 0.

**The cause is which term gets credited, not the bound being loose in general.** Per unbuilt
`(p,j)` the completion must cancel `alpha_p ~ 1500-2000` and credits `w * walk_min ~ 4-18`
(0.2-1.2%), while the route-travel term it ignores -- the cheapest detour that could touch
`j`, `beta * delta_j` -- is worth 350-1750 (25-85%). With `walk_cost_weight = 0.1` against
`route_regularization_weight = 10.0`, crediting walking is crediting the wrong term by two
orders of magnitude, so `gamma_pj` lands at essentially `alpha_p`.

The consequence is not "more iterations" but no convergence: n=15 s=3 stops at the 900 s wall
after 657 iterations / 1971 cuts with a 4.9% gap, n=20 s=3 after 460 iterations / 1380 cuts
with 28% (full CG: 6/10 and 9/13, converged). It converges only at n=10, where 77 cuts is
comparable to the 86 station sets that exist -- the cut behaves like a no-good cut on its
anchor.

**A free safety property**: the strong-duality assertion
`sum(alpha) - sum(Gamma .* yhat) == objective` still holds, because the completion only ever
touches stations with `yhat_j = 0`. So if the completion ever raised a `gamma` on a BUILT
station, that assertion fires immediately.

# What makes a CG subproblem's cut valid -- and it is NOT pool fixity

The requirement is that the extracted `(alpha, gamma)` be feasible for the dual of the
**full-universe** problem. Enumeration gets that by containing the universe. CG gets it by
proving nothing improving remains: at CG convergence every column in the universe -- priced
or not -- satisfies `f_c - sum alpha + sum gamma >= 0`, which IS its dual constraint. So:

- a cut taken from a **converged** subproblem CG is globally valid, and stays valid as the
  pool grows later (the full dual's feasible set does not depend on the pool);
- a cut taken from a **budget-stopped** CG is NOT valid -- those duals are feasible only for
  the restricted dual, so the cut can over-estimate the true second-stage cost and prune the
  optimum. `solve_subproblem` therefore refuses to derive a cut unless pricing exhausted.

A non-converged CG still yields a valid UPPER bound (its restricted optimum is achievable by
pooled columns), just no cut.

Two consequences for the implementation. The pool is deliberately **accumulated across
Benders iterations** per scenario -- pure warm start, and sound by the above. And pricing must
search the **full station set**, not only the stations built at `yhat`: a column through an
unbuilt station still has a dual constraint that has to be satisfied, and the seemingly
useless columns it yields are what let that station's linking dual rise to the value that
makes the cut valid at other `y`.

# `max_stops` -- the enumeration cap, and a real restriction

`enumerate_joint_routing_assignment_columns` is exponential in `max_stops` on two axes at
once (the physical-route DFS, then the per-route cartesian product over multi-certified
passengers), and throws rather than truncating when it blows past `max_routes`. `4` is
the largest value measured tractable on the reference instances (16,320 columns at a
10-station / 8-pair instance), so it is the default here rather than the formulation's own
value.

**When it is below the formulation's own `max_stops`, the run's optimality claim narrows
with it** -- the answer is optimal over routes of at most this many stops, and a longer
route can beat it. The build records that as
`metadata["benders_optimality_scope"] = "max_stops_restricted"` (versus
`"full_route_universe"` when no narrowing happened), alongside
`benders_subproblem_max_stops` and `benders_formulation_max_stops`, in exactly the spirit
of `CGSolver`'s `cg_optimality_scope`. Read it before pooling a `BendersSolver` objective
with a `DirectMIPSolver` one. `nothing` disables the cap and enumerates the formulation's
own universe.

# The rest

`max_routes`/`enumeration_time_limit_sec` are the enumerator's own guard rails, passed
straight through. `time_limit_sec` bounds each individual subproblem LP solve
(`nothing` = no limit); a subproblem that hits it returns a non-optimal status, which
`solve_subproblem` treats as a hard error rather than a weak cut, since a truncated LP's
duals are not a valid underestimator.

`:column_generation` adds `pricing` (a `CGPricingConfig` -- the pricer, defaulting to the
formulation's own, i.e. `:exact`), `reduced_cost_tol`, `max_cg_iterations`, and
`cg_pricing_time_limit_sec` (per pricing round, per scenario).

Accepted pricers are those whose exhaustion covers the FULL route universe, because that is
what licenses a cut:

- `:exact` / `:darp` / `:darp_modified` -- exhaust by searching the whole revisit-tolerant
  universe.
- `:relaxed_cluster` / `:relaxed_cluster_two_tier` -- exhaust by CERTIFYING: the relaxation
  lower-bounds every real route's reduced cost, so exhausting it without finding anything
  below the tolerance proves no real improving column exists. The certificate covers the
  full universe, so it licenses a cut exactly as an exhaustive search does. These require a
  `relaxed_cluster_count`, and are the mode to use past the sizes where `:exact` still
  exhausts (the measured CG frontier is n<=20 all scenarios, n=25 to <=5 scenarios, n=30
  only s=1). Their known weak point is the certification rate itself (0/31 one-shot, 4/10 at
  n=40 with no-good cut rounds), and here a certification attempt runs once per scenario per
  Benders iteration: a REFUTED attempt is harmless -- it harvests real columns and acts as
  that round's pricing -- but an INCONCLUSIVE one blocks the cut and stalls the loop, which
  `verbose` is there to make visible.

`:station_simple` is rejected as UNSOUND for this role: elementary-only exhaustion proves no
elementary column improves, so its duals are feasible for the elementary-restricted dual only
and a cut from them can prune the optimum.

`verbose=true` prints one line per inner CG iteration (scenario, columns priced/added,
whether pricing exhausted, elapsed). Worth having on for any long run: with a per-round
pricing budget of several hundred seconds times scenarios times Benders iterations, a silent
run gives no way to tell "still pricing productively" from "stuck", and the aggregate
metadata only arrives once the whole solve finishes.
"""
struct BendersSubproblemConfig
    oracle::Symbol
    max_stops::Union{Nothing, Int}
    max_routes::Int
    enumeration_time_limit_sec::Float64
    time_limit_sec::Union{Nothing, Float64}
    pricing::CGPricingConfig
    reduced_cost_tol::Float64
    max_cg_iterations::Int
    cg_pricing_time_limit_sec::Float64
    verbose::Bool
    lpo_completion::Symbol
    lpo_max_rounds::Int
    lpo_pricing_time_limit_sec::Float64

    function BendersSubproblemConfig(;
            oracle::Symbol=:direct_enumeration,
            max_stops::Union{Nothing, Int, Missing}=missing,
            max_routes::Int=200_000,
            enumeration_time_limit_sec::Number=180.0,
            time_limit_sec::Union{Nothing, Number}=nothing,
            pricing::CGPricingConfig=CGPricingConfig(),
            reduced_cost_tol::Number=1e-6,
            max_cg_iterations::Int=500,
            cg_pricing_time_limit_sec::Number=300.0,
            verbose::Bool=false,
            lpo_completion::Symbol=:separation,
            lpo_max_rounds::Int=25,
            lpo_pricing_time_limit_sec::Number=60.0,
        )
        oracle in (:direct_enumeration, :column_generation,
                   :column_generation_activated,
                   :column_generation_activated_lpo,
                   :column_generation_warm_start) || throw(ArgumentError(
            "unsupported Benders subproblem oracle $(repr(oracle)); expected " *
            ":direct_enumeration, :column_generation, :column_generation_activated, " *
            ":column_generation_activated_lpo or " *
            ":column_generation_warm_start",
        ))
        # `max_stops` defaults PER ORACLE, which is why the keyword takes `missing` rather
        # than a plain value: enumeration needs the cap (its pool is exponential in it), and
        # column generation does not (the pricer respects the formulation's own `max_stops`).
        # Defaulting to 4 for both would silently narrow every CG run's route universe --
        # exactly the trap this type's `max_stops` section warns about, applied by accident.
        resolved_max_stops = if max_stops === missing
            # Only the enumeration oracle needs a cap (its pool is exponential in max_stops);
            # every CG-based oracle prices on demand and takes the formulation's own value.
            oracle === :direct_enumeration ? 4 : nothing
        else
            max_stops
        end
        isnothing(resolved_max_stops) || resolved_max_stops >= 2 ||
            throw(ArgumentError("max_stops must be at least 2"))
        max_routes > 0 || throw(ArgumentError("max_routes must be positive"))
        enumeration_time_limit_sec > 0 ||
            throw(ArgumentError("enumeration_time_limit_sec must be positive"))
        isnothing(time_limit_sec) || time_limit_sec > 0 ||
            throw(ArgumentError("time_limit_sec must be positive"))
        reduced_cost_tol >= 0 ||
            throw(ArgumentError("reduced_cost_tol must be non-negative"))
        max_cg_iterations > 0 ||
            throw(ArgumentError("max_cg_iterations must be positive"))
        cg_pricing_time_limit_sec > 0 ||
            throw(ArgumentError("cg_pricing_time_limit_sec must be positive"))
        lpo_completion in (:separation, :route_free) || throw(ArgumentError(
            "unsupported lpo_completion $(repr(lpo_completion)); expected :separation " *
            "(the default, and the only one measured to recover cut strength) or " *
            ":route_free",
        ))
        lpo_max_rounds > 0 || throw(ArgumentError("lpo_max_rounds must be positive"))
        lpo_pricing_time_limit_sec > 0 ||
            throw(ArgumentError("lpo_pricing_time_limit_sec must be positive"))
        # ONLY EXHAUSTIVE-EQUIVALENT PRICERS. A Benders cut is licensed by full-universe
        # exhaustion, so a pricer that exhausts a strict SUBSET of the universe cannot
        # license one -- see the rejection message for why `:station_simple` specifically is
        # unsound here despite being a perfectly good pricer for the CG master.
        pricing.mode in (nothing, :exact, :darp, :darp_modified,
                         :relaxed_cluster, :relaxed_cluster_two_tier) || throw(ArgumentError(
            "Benders subproblem pricing mode $(repr(pricing.mode)) cannot license a " *
            "Benders cut; use :exact (default), :darp or :darp_modified, which all search " *
            "the full revisit-tolerant route universe and are exhaustive-equivalent.\n" *
            "  :station_simple searches ELEMENTARY routes only, so its exhaustion proves " *
            "no elementary column improves -- not that no column improves. Its duals are " *
            "then feasible for the elementary-restricted dual only, and a cut built from " *
            "them can over-estimate the true second-stage cost and prune the optimum. " *
            "(`_cg_pricing_universe_is_restricted(:station_simple)` is already `true` and " *
            "its scope label is \"elementary_routes_only\"; " *
            "notes/2026-07-27 measured 70-76% objective error from exactly this class of " *
            "invalid cut.)\n" *
            "  :relaxed_cluster / :relaxed_cluster_two_tier ARE accepted -- see this " *
            "type's docstring. They require a `relaxed_cluster_count` (CGPricingConfig " *
            "enforces that pairing).",
        ))
        new(
            oracle, resolved_max_stops, max_routes, Float64(enumeration_time_limit_sec),
            isnothing(time_limit_sec) ? nothing : Float64(time_limit_sec),
            pricing, Float64(reduced_cost_tol), max_cg_iterations,
            Float64(cg_pricing_time_limit_sec), verbose,
            lpo_completion, lpo_max_rounds, Float64(lpo_pricing_time_limit_sec),
        )
    end
end
