"""
RouteVehicleCapacityModel — non-temporal route-based model with α = C (vehicle capacity).

Variant of TwoStageRouteWithTimeModel with the time dimension removed.
OD demand is aggregated over all time within each scenario.
Routes are generated by a non-temporal BFS (no time windows, no wait-time constraint).

The covering constraint uses vehicle capacity C as a flat upper bound rather than actual
per-leg passenger counts:

    Σ_{r: (j,k)∈r} C · θ^r_s  ≥  Σ_{(o,d)} Q_s[(o,d)] · x[s][od][pair]
"""

export RouteVehicleCapacityModel


"""
    RouteVehicleCapacityModel <: AbstractODModel

Two-stage stochastic station selection with time-indexed route and vehicle capacity
constraints (new formulation from March 17 journal note).

Introduces per-route, per-class passenger variables θ^r_{jkts} and explicit segment
capacity constraints using β^r_{jktm}. Route activation uses γ_s^r ∈ {0,1}.

Covering constraints (replacing the single α-based constraint):

    (i)  α_{jkts} = Σ_{p: t(p)=t} Q_{s,t}[(o,d)] · x[s][od][pair]   (inlined)
    (ii) α_{jkts} ≤ Σ_r θ^r_{jkts}                                   ∀ j,k,t,s
    (iii) Σ_{j,k,t} β^r_{jktm} θ^r_{jkts} ≤ Cap_r · γ_s^r           ∀ r,m,s

# Fields
- `k::Int`: Stations to activate per scenario (second stage)
- `l::Int`: Stations to build (first stage)
- `route_regularization_weight::Float64`: μ — penalty per unit route travel time activated
- `repositioning_time::Float64`: ρ — constant repositioning time (seconds) added to route travel time in objective per deployment
- `vehicle_capacity::Int`: Cap_r — vehicle capacity used in segment capacity constraints
- `max_route_travel_time::Union{Float64,Nothing}`: Upper bound on route travel time filter
- `max_walking_distance::Float64`: Required walking limit; prunes valid (j,k) pairs
- `max_detour_time::Float64`: Max extra in-vehicle seconds vs direct trip
- `max_detour_ratio::Float64`: Max ratio `in_vehicle/direct - 1`
- `time_window_sec::Int`: Width of time bucket t (seconds); default 300 (5 min)
- `use_lazy_constraints::Bool`: If true, constraints (ii) and (iii) are submitted via a
  lazy callback instead of upfront; default false
- `routes_file::Union{String,Nothing}`: Path to `routes_input.csv` (route_id, station_ids,
  travel_time). When set, routes are loaded from this CSV instead of generated by DFS.
- `alpha_profile_file::Union{String,Nothing}`: Path to `alpha_profile.csv` (route_id,
  pickup_id, dropoff_id, value). Alpha values are used as warm-start hints for α variables.
  Requires `routes_file` to be set.
"""
struct RouteVehicleCapacityModel <: AbstractODModel
    k::Int
    l::Int
    route_regularization_weight::Float64
    repositioning_time::Float64
    vehicle_capacity::Int
    max_route_travel_time::Union{Float64, Nothing}
    max_walking_distance::Float64
    max_detour_time::Float64
    max_detour_ratio::Float64
    time_window_sec::Int
    use_lazy_constraints::Bool
    max_stations_visited::Int
    routes_file        :: Union{String, Nothing}
    alpha_profile_file :: Union{String, Nothing}

    function RouteVehicleCapacityModel(
            k::Int,
            l::Int;
            route_regularization_weight::Number = 1.0,
            repositioning_time::Number = 20.0,
            vehicle_capacity::Int = 18,
            max_route_travel_time::Union{Number, Nothing} = nothing,
            max_walking_distance::Number = 300,
            max_detour_time::Number = 1200,
            max_detour_ratio::Number = 2.0,
            time_window_sec::Int = 3600,
            use_lazy_constraints::Bool = false,
            max_stations_visited::Int = typemax(Int),
            routes_file        :: Union{String, Nothing} = nothing,
            alpha_profile_file :: Union{String, Nothing} = nothing
        )

        k > 0 || throw(ArgumentError("k must be positive"))
        l >= k || throw(ArgumentError("l must be >= k"))
        route_regularization_weight >= 0 ||
            throw(ArgumentError("route_regularization_weight must be non-negative"))
        vehicle_capacity > 0 || throw(ArgumentError("vehicle_capacity must be positive"))
        time_window_sec > 0 || throw(ArgumentError("time_window_sec must be positive"))
        max_stations_visited >= 1 ||
            throw(ArgumentError("max_stations_visited must be >= 1"))
        !isnothing(routes_file) && !isfile(routes_file) &&
            throw(ArgumentError("routes_file not found: $routes_file"))
        !isnothing(alpha_profile_file) && !isfile(alpha_profile_file) &&
            throw(ArgumentError("alpha_profile_file not found: $alpha_profile_file"))
        isnothing(routes_file) && !isnothing(alpha_profile_file) &&
            throw(ArgumentError("alpha_profile_file requires routes_file to be set"))

        mdt  = Float64(max_detour_time)
        mdr  = Float64(max_detour_ratio)
        mrtt = isnothing(max_route_travel_time) ? nothing : Float64(max_route_travel_time)

        mdt >= 0.0 || throw(ArgumentError("max_detour_time must be non-negative"))
        mdr >= 0.0 || throw(ArgumentError("max_detour_ratio must be non-negative"))
        max_walking_distance >= 0 ||
            throw(ArgumentError("max_walking_distance must be non-negative"))

        new(k, l, Float64(route_regularization_weight), Float64(repositioning_time), vehicle_capacity, mrtt,
            Float64(max_walking_distance), mdt, mdr, time_window_sec, use_lazy_constraints,
            max_stations_visited, routes_file, alpha_profile_file)
    end
end
