"""
RouteAlphaCapacityModel and RouteVehicleCapacityModel — non-temporal route-based models.

Variants of TwoStageRouteWithTimeModel with the time dimension removed.
OD demand is aggregated over all time within each scenario.
Routes are generated by a non-temporal BFS (no time windows, no wait-time constraint).

The two models differ only in the capacity coefficient in the route-covering constraint:
- RouteAlphaCapacityModel: α^r_{j,k} = actual per-leg passengers from route BFS
- RouteVehicleCapacityModel: α = C (vehicle capacity, flat upper bound)
"""

export RouteAlphaCapacityModel, RouteVehicleCapacityModel


"""
    RouteAlphaCapacityModel <: AbstractODModel

Two-stage stochastic station selection with non-temporal route-based capacity constraints.

OD pairs are aggregated over all time within each scenario (no time-window index).
Routes are pre-generated sequences of VBS stops via non-temporal BFS.
The covering constraint uses actual per-leg passenger counts (α):

    Σ_{r: (j,k)∈r} α^r_{j,k} · θ^r_s  ≥  Σ_{(o,d)} Q_s[(o,d)] · x[s][od][pair]

# Fields
- `k::Int`: Stations to activate per scenario (second stage)
- `l::Int`: Stations to build (first stage)
- `route_regularization_weight::Float64`: μ — penalty per unit route travel time activated
- `vehicle_capacity::Int`: Max passengers on board at any time (BFS feasibility)
- `max_route_travel_time::Union{Float64,Nothing}`: Upper bound on route travel time filter
- `max_walking_distance::Float64`: Required walking limit; prunes valid (j,k) pairs
- `max_detour_time::Float64`: Max extra in-vehicle seconds vs direct trip
- `max_detour_ratio::Float64`: Max ratio `in_vehicle/direct - 1`
"""
struct RouteAlphaCapacityModel <: AbstractODModel
    k::Int
    l::Int
    route_regularization_weight::Float64
    vehicle_capacity::Int
    max_route_travel_time::Union{Float64, Nothing}
    max_walking_distance::Float64
    max_detour_time::Float64
    max_detour_ratio::Float64

    function RouteAlphaCapacityModel(
            k::Int,
            l::Int;
            route_regularization_weight::Number = 1.0,
            vehicle_capacity::Int = 18,
            max_route_travel_time::Union{Number, Nothing} = nothing,
            max_walking_distance::Number = 300,
            max_detour_time::Number = 1200,
            max_detour_ratio::Number = 2.0
        )

        k > 0 || throw(ArgumentError("k must be positive"))
        l >= k || throw(ArgumentError("l must be >= k"))
        route_regularization_weight >= 0 ||
            throw(ArgumentError("route_regularization_weight must be non-negative"))
        vehicle_capacity > 0 || throw(ArgumentError("vehicle_capacity must be positive"))

        mdt  = Float64(max_detour_time)
        mdr  = Float64(max_detour_ratio)
        mrtt = isnothing(max_route_travel_time) ? nothing : Float64(max_route_travel_time)

        mdt >= 0.0 || throw(ArgumentError("max_detour_time must be non-negative"))
        mdr >= 0.0 || throw(ArgumentError("max_detour_ratio must be non-negative"))
        max_walking_distance >= 0 ||
            throw(ArgumentError("max_walking_distance must be non-negative"))

        new(k, l, Float64(route_regularization_weight), vehicle_capacity, mrtt,
            Float64(max_walking_distance), mdt, mdr)
    end
end


"""
    RouteVehicleCapacityModel <: AbstractODModel

Two-stage stochastic station selection with non-temporal route-based capacity constraints.

Identical to `RouteAlphaCapacityModel` except the covering constraint uses vehicle
capacity C as a flat upper bound rather than actual per-leg passenger counts:

    Σ_{r: (j,k)∈r} C · θ^r_s  ≥  Σ_{(o,d)} Q_s[(o,d)] · x[s][od][pair]

# Fields
- `k::Int`: Stations to activate per scenario (second stage)
- `l::Int`: Stations to build (first stage)
- `route_regularization_weight::Float64`: μ — penalty per unit route travel time activated
- `vehicle_capacity::Int`: C — used both in BFS feasibility and covering constraint coefficient
- `max_route_travel_time::Union{Float64,Nothing}`: Upper bound on route travel time filter
- `max_walking_distance::Float64`: Required walking limit; prunes valid (j,k) pairs
- `max_detour_time::Float64`: Max extra in-vehicle seconds vs direct trip
- `max_detour_ratio::Float64`: Max ratio `in_vehicle/direct - 1`
"""
struct RouteVehicleCapacityModel <: AbstractODModel
    k::Int
    l::Int
    route_regularization_weight::Float64
    vehicle_capacity::Int
    max_route_travel_time::Union{Float64, Nothing}
    max_walking_distance::Float64
    max_detour_time::Float64
    max_detour_ratio::Float64

    function RouteVehicleCapacityModel(
            k::Int,
            l::Int;
            route_regularization_weight::Number = 1.0,
            vehicle_capacity::Int = 18,
            max_route_travel_time::Union{Number, Nothing} = nothing,
            max_walking_distance::Number = 300,
            max_detour_time::Number = 1200,
            max_detour_ratio::Number = 2.0
        )

        k > 0 || throw(ArgumentError("k must be positive"))
        l >= k || throw(ArgumentError("l must be >= k"))
        route_regularization_weight >= 0 ||
            throw(ArgumentError("route_regularization_weight must be non-negative"))
        vehicle_capacity > 0 || throw(ArgumentError("vehicle_capacity must be positive"))

        mdt  = Float64(max_detour_time)
        mdr  = Float64(max_detour_ratio)
        mrtt = isnothing(max_route_travel_time) ? nothing : Float64(max_route_travel_time)

        mdt >= 0.0 || throw(ArgumentError("max_detour_time must be non-negative"))
        mdr >= 0.0 || throw(ArgumentError("max_detour_ratio must be non-negative"))
        max_walking_distance >= 0 ||
            throw(ArgumentError("max_walking_distance must be non-negative"))

        new(k, l, Float64(route_regularization_weight), vehicle_capacity, mrtt,
            Float64(max_walking_distance), mdt, mdr)
    end
end
