# Docs build. Run it through SLURM, never on a login node -- loading StationSelection loads
# Gurobi: `sbatch scripts/sbatch_build_docs.sh`. That script explains why Documenter comes
# from a stacked `@station-docs-tools` environment instead of a docs/Project.toml (short
# version: a fresh resolve re-runs Gurobi's build step, which hangs).
#
# HOW THIS BUILD WORKS
#
# No HTML is written by hand, and no page names a source file by hand.
#
#   docs/pages/**/*.md   prose, with `{{autodocs <path>...}}` markers   <- the only thing edited
#   docs/src/**/*.md     generated: markers expanded to file lists      <- gitignored
#   docs/build/**/*.html generated by Documenter from the docstrings     <- gitignored
#
# Documenter matches `Pages` entries with `endswith` on the source path, so a bare directory
# does not match and files must be enumerated. `expand_markers` enumerates them by walking
# `src/`, so a new source file shows up on the right page with no edit anywhere.
#
# Marker syntax, one per line:
#   {{autodocs opt/solvers/cg}}                       every .jl under that path
#   {{autodocs opt/solvers/benders opt/optimize/...}}  several paths, in order
#   {{autodocs opt/optimize !opt/optimize/.../benders}} `!` excludes a subtree
#   {{autodocs-rest}}                                  whatever no other page claimed
#
# Two invariants, both enforced rather than trusted:
#   * a file may be claimed by only ONE marker (a second claim errors) -- claiming twice is
#     what produces Documenter's duplicate-docstring warnings;
#   * a file claimed by NO marker still renders, on the page holding `{{autodocs-rest}}`,
#     so adding a subsystem cannot silently drop it from the docs.
using Documenter
using StationSelection

const SRC = normpath(joinpath(@__DIR__, "..", "src"))
const PAGES_IN = joinpath(@__DIR__, "pages")
const PAGES_OUT = joinpath(@__DIR__, "src")

"Every `.jl` under `path` (a file or a directory), relative to the module root, sorted."
function jl_under(path::AbstractString)
    root = normpath(joinpath(SRC, path))
    if isfile(root)
        return [relpath(root, SRC)]
    end
    isdir(root) || error("docs: no such source path `$path`")
    out = String[]
    for (dir, _, files) in walkdir(root), f in files
        endswith(f, ".jl") && push!(out, relpath(joinpath(dir, f), SRC))
    end
    return sort(out)
end

function autodocs_block(files::Vector{String})
    isempty(files) && return ""
    io = IOBuffer()
    println(io, "```@autodocs")
    println(io, "Modules = [StationSelection]")
    println(io, "Pages = [")
    foreach(f -> println(io, "    ", repr(f), ","), files)
    println(io, "]")
    print(io, "```")
    return String(take!(io))
end

# `\s+` is load-bearing: without it `{{autodocs-rest}}` matches MARKER with a captured
# path of "-rest". REST_MARKER is also tested FIRST, for the same reason.
const MARKER = r"^\{\{autodocs\s+([^}]*)\}\}$"
const REST_MARKER = r"^\{\{autodocs-rest\}\}$"

"""
Expand every marker in `docs/pages/` into `docs/src/`, returning the claimed-file set.

Runs in two passes because `{{autodocs-rest}}` needs to know what every other marker took.
"""
function expand_markers()
    sources = String[]
    for (dir, _, files) in walkdir(PAGES_IN), f in files
        endswith(f, ".md") && push!(sources, relpath(joinpath(dir, f), PAGES_IN))
    end
    sort!(sources)

    claimed = Dict{String, String}()   # source file => the page that claimed it
    resolved = Dict{String, Vector{Union{String, Vector{String}}}}()

    for rel in sources
        parts = Union{String, Vector{String}}[]
        for line in eachline(joinpath(PAGES_IN, rel))
            stripped = strip(line)
            if occursin(REST_MARKER, stripped)
                push!(parts, ["\0REST"])
                continue
            end
            m = match(MARKER, stripped)
            if m === nothing
                push!(parts, line)
                continue
            end
            args = split(strip(m.captures[1]))
            isempty(args) && error("docs: empty {{autodocs}} marker in $rel")
            includes = filter(a -> !startswith(a, "!"), args)
            excludes = [chop(a; head=1, tail=0) for a in args if startswith(a, "!")]
            dropped = isempty(excludes) ? String[] : reduce(vcat, jl_under.(excludes))
            files = setdiff(reduce(vcat, jl_under.(includes)), dropped)
            for f in files
                haskey(claimed, f) && error(
                    "docs: `$f` claimed by both $(claimed[f]) and $rel; give it to one page")
                claimed[f] = rel
            end
            push!(parts, sort(files))
        end
        resolved[rel] = parts
    end

    leftover = sort(collect(setdiff(Set(jl_under(".")), keys(claimed))))
    if !isempty(leftover)
        @info "docs: $(length(leftover)) source file(s) claimed by no page -> Other" leftover
    end

    for (rel, parts) in resolved
        out = joinpath(PAGES_OUT, rel)
        mkpath(dirname(out))
        open(out, "w") do io
            for p in parts
                if p isa Vector
                    println(io, autodocs_block(p == ["\0REST"] ? leftover : p))
                else
                    println(io, p)
                end
            end
        end
    end
    return claimed
end

isdir(PAGES_OUT) && rm(PAGES_OUT; recursive=true)
expand_markers()

makedocs(
    sitename="StationSelection.jl",
    modules=[StationSelection],
    format=Documenter.HTML(
        prettyurls=false,
        # Several docstrings in this package are pages in their own right, so the default
        # 200 KiB page cap trips on them. Warn, don't fail: an over-large page is a
        # readability signal to act on, not a reason to have no docs.
        size_threshold=nothing,
        size_threshold_warn=200 * 1024,
    ),
    pages=[
        "Home" => "index.md",
        "Problems" => "problems.md",
        "Formulations" => "formulations.md",
        "Model construction" => "construction.md",
        "Solvers" => [
            "Overview" => "solvers/index.md",
            "DirectMIPSolver" => "solvers/direct.md",
            "CGSolver" => "solvers/cg.md",
            "BendersSolver" => "solvers/benders.md",
        ],
        "Pricing & label setting" => "pricing.md",
        "Joint routing pricers" => "pricers.md",
        "Relaxed-cluster relaxation" => "relaxed_cluster.md",
        "Certification" => "certification.md",
        "Results & solve status" => "results.md",
        "Data & mappings" => "data.md",
        "Model building blocks" => "building_blocks.md",
        "Instance generation" => "generators.md",
        "Analysis & output" => "analysis.md",
        "Other" => "other.md",
    ],
    checkdocs=:exports,
    warnonly=true,
    # No "edit on GitHub" links, for two reasons. There is no public repository to link to
    # (this package is a submodule of a private project), and resolving those links makes
    # Documenter call `Pkg.dependencies()` over the package's whole graph -- which FAILS
    # here: the Manifest still carries an `MbedTLS_jll` entry, dropped from the stdlib in
    # Julia 1.12, and Pkg errors with "could not find source path" (job 22476156). Nothing
    # else in the package touches `Pkg.dependencies()`, which is why the test suite has
    # never noticed. `warnonly` does not cover it -- it is a Pkg error, not a doc warning.
    remotes=nothing,
)
